name: Continuous Integration for Java Project
on:
    push:
      branches:
        - main
        - dev
    workflow_dispatch:
    pull_request:
        types:
          - opened
          - synchronize
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'zulu'

            - name: Show Java version
              run: "java -version"
            
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: 'mvn compile'  
            
            - name: Set permissions
              run: chmod 755 ./mvnw
            
            - name: Build project
              run: ./mvnw clean package
              
            - name: Check build project
              run: "ls -la"

            - name: Test application
              run: 'mvn test'
          
              
           
